In [59]:
from os import listdir, makedirs
from os.path import isfile, isdir, join

import numpy as np
import pandas as pd

flare_file_path = './output/non_ar_matched.csv'
headers_path = '../sharps-headers/'
output_merged_sharp_path = '../annotated-new-data/'

sharp_last_date = pd.to_datetime('2017-06-30', format='%Y-%m-%d')

noaa_map_path = './all_harps_with_noaa_ars.txt'
noaa_map = False  # global variable
downloads_noaa_map = False # global variable

from flare_reader import get_flare_dataframe, match_harp_to_noaa, get_harp_to_noaa_map
from aia_flare_integration import get_aia_flare_dataframe, get_goes_flare_dataframe

noaa_map = get_harp_to_noaa_map()
ufdf = get_flare_dataframe(flare_file_path)

# ufdf['end_time'] < sharp_last_date

In [60]:
ufdf = ufdf[ ufdf['end_time'] < sharp_last_date]
# print ufdf.shape[0]

In [61]:
cols = ['goes_location', 'aia_location', 'noaa_active_region_aia', 'noaa_active_region_goes'] 
aia_only = ufdf[(pd.isnull(ufdf['noaa_active_region_goes']))]
both = ufdf[~(pd.isnull(ufdf['noaa_active_region_goes']))]
goes_only = ufdf[(pd.isnull(ufdf['noaa_active_region_aia']))]
both = both[~(pd.isnull(both['noaa_active_region_aia']))]

In [4]:
foi_aia = aia_only[ aia_only['noaa_active_region_aia']!=0 ]
# foi_aia.head()
foi_aia.shape[0]

37

In [5]:
foi_goes = goes_only[goes_only['noaa_active_region_goes']!=0]
# foi_goes.head()
foi_goes.shape[0]

247

In [6]:
foi_both = both[ ~((both['noaa_active_region_aia'] == 0) & (both['noaa_active_region_goes'] == 0)) ]
foi_both.shape[0]

640

In [7]:
foi = pd.concat( [foi_both, foi_goes, foi_aia] )
foi.shape[0]

924

In [62]:
def get_noaa_to_harp_map(noaa_map):
    noaa_to_harp = {}
    for harp,noaa_list in noaa_map.to_dict()['NOAA_ARS'].iteritems():
        for noaa in noaa_list.split(','):
            harps = noaa_to_harp.get(noaa, [])
            harps.append(harp)
            noaa_to_harp[noaa] = harps
    return noaa_to_harp

noaa_to_harps = get_noaa_to_harp_map(noaa_map)

In [63]:
aia_harps = ufdf['noaa_active_region_aia'].apply( lambda x: noaa_to_harps.get(str(int(x)), []) if ~np.isnan(x) and x!=0 else [])
goes_harps = ufdf['noaa_active_region_goes'].apply( lambda x: noaa_to_harps.get(str(int(x)), []) if ~np.isnan(x) and x!=0 else [])
harps = pd.DataFrame({'aia': aia_harps2,'goes':goes_harps2})

             aia    goes
flare_id
69          [86]      []
70          [86]      []
293           []      []
350           []      []
683           []      []
684           []      []
1776      [1621]      []
1777      [1621]  [1621]
1778      [1621]      []
1779      [1621]  [1621]
1780      [1621]  [1621]
1781      [1621]  [1621]
1782      [1621]      []
1783      [1621]  [1621]
1784      [1621]  [1621]
1785      [1621]  [1621]
1791      [1621]  [1621]
1797      [1621]  [1621]
1798      [1621]  [1621]
1799      [1621]  [1621]
1813      [1621]      []
1816      [1621]  [1621]
1819      [1621]  [1621]
1923      [1677]  [1677]
1930      [1677]  [1677]
1968      [1727]      []
1971      [1750]  [1750]
1972      [1750]  [1750]
1973      [1750]      []
1974      [1750]  [1750]
...          ...     ...
11036     [1834]      []
11037     [1834]      []
11038     [1834]      []
11042     [1907]      []
11043     [1930]      []
11044     [1907]      []
11045     [1931]      []
11046     [1931]      []
11047     [1946]      []
11048     [1962]      []
11050     [1962]      []
11051     [1962]      []
11055     [1990]      []
11165     [2758]      []
11166     [2758]      []
11207     [3856]      []
11208     [3856]      []
11209     [3856]      []
11210     [3856]      []
11213     [4225]      []
11245         []      []
11258     [4800]      []
11259     [4817]      []
11267         []      []
11328         []      []
11425         []      []
11454     [7058]      []
11455     [7058]      []
11456     [7058]      []
11457     [7058]      []

[1575 rows x 2 columns]

In [65]:
harp_lists = harps.apply( lambda x : list(set(x['aia'] + x['goes'])), axis='columns' )
ufdf['harps'] = harp_lists
cols.append('harps')

,goes_location,aia_location,noaa_active_region_aia,noaa_active_region_goes,harps
flare_id,,,,,
69,"(0, 0)",POINT(62 12),11087.0,11091.0,[86]
70,"(0, 0)",POINT(61 12),11087.0,11091.0,[86]
293,"(0, 0)",POINT(62 -24),0.0,0.0,[]
350,"(0, 0)",POINT(-62 32),0.0,0.0,[]
683,"(0, 0)",POINT(-70 8),0.0,0.0,[]
684,"(0, 0)",POINT(-8 22),0.0,0.0,[]
1776,"(0, 0)",POINT(-64 -23),11471.0,0.0,[1621]
1777,"(-63, -24)",POINT(-63 -23),11471.0,11471.0,[1621]
1778,"(0, 0)",POINT(-62 -23),11471.0,0.0,[1621]
1779,"(-62, -22)",POINT(-62 -22),11471.0,11471.0,[1621]
1780,"(0, 0)",POINT(-59 -23),11471.0,11471.0,[1621]
1781,"(-59, -24)",POINT(-59 -22),11471.0,11471.0,[1621]
1782,"(0, 0)",POINT(-60 -22),11471.0,0.0,[1621]
1783,"(-57, -26)",POINT(-56 -24),11471.0,11471.0,[1621]
1784,"(-38, -19)",POINT(-37 -19),11471.0,11470.0,[1621]
1785,"(-38, -20)",POINT(-36 -20),11471.0,11471.0,[1621]
1791,"(-23, -22)",POINT(-23 -22),11471.0,11471.0,[1621]
1797,"(16, -17)",POINT(15 -18),11471.0,11470.0,[1621]
1798,"(0, 0)",POINT(22 -21),11471.0,11471.0,[1621]
1799,"(0, 0)",POINT(30 -15),11470.0,11470.0,[1621]
1813,"(0, 0)",POINT(39 -19),11471.0,0.0,[1621]
1816,"(0, 0)",POINT(43 -19),11471.0,11471.0,[1621]
1819,"(46, -19)",POINT(49 -20),11471.0,11471.0,[1621]
1923,"(39, 23)",POINT(40 22),11491.0,11491.0,[1677]
1930,"(0, 0)",POINT(64 22),11491.0,11491.0,[1677]
1968,"(0, 0)",POINT(69 -22),11497.0,0.0,[1727]
1971,"(0, 0)",POINT(-70 -16),11504.0,11504.0,[1750]
1972,"(0, 0)",POINT(-66 -15),11504.0,11504.0,[1750]
1973,"(0, 0)",POINT(16 -11),11505.0,0.0,[1750]
1974,"(21, -16)",POINT(20 -16),11504.0,11504.0,[1750]
...,...,...,...,...,...
11036,NaN,POINT(31 -13),11520.0,NaN,[1834]
11037,NaN,POINT(69 -18),11519.0,NaN,[1834]
11038,NaN,POINT(64 -15),11519.0,NaN,[1834]
11042,NaN,POINT(-56 -21),11540.0,NaN,[1907]
11043,NaN,POINT(-63 -12),11542.0,NaN,[1930]
11044,NaN,POINT(-5 -29),11541.0,NaN,[1907]
11045,NaN,POINT(45 24),11543.0,NaN,[1931]
11046,NaN,POINT(43 24),11543.0,NaN,[1931]
11047,NaN,POINT(-53 18),11548.0,NaN,[1946]
11048,NaN,POINT(36 14),11554.0,NaN,[1962]
11050,NaN,POINT(54 15),11554.0,NaN,[1962]
11051,NaN,POINT(67 14),11554.0,NaN,[1962]
11055,NaN,POINT(56 -20),11562.0,NaN,[1990]
11165,NaN,POINT(-54 -20),11756.0,NaN,[2758]
11166,NaN,POINT(16 -15),11756.0,NaN,[2758]
11207,NaN,POINT(14 -12),12010.0,NaN,[3856]
11208,NaN,POINT(14 -13),12010.0,NaN,[3856]
11209,NaN,POINT(15 -13),12010.0,NaN,[3856]
11210,NaN,POINT(24 -10),12010.0,NaN,[3856]
11213,NaN,POINT(48 -20),12087.0,NaN,[4225]
11245,NaN,POINT(47 -12),12151.0,NaN,[]
11258,NaN,POINT(63 -13),12208.0,NaN,[4800]
11259,NaN,POINT(26 -14),12209.0,NaN,[4817]
11267,NaN,POINT(-40 -19),0.0,NaN,[]
11328,NaN,POINT(13 -17),0.0,NaN,[]
11425,NaN,POINT(-40 -8),0.0,NaN,[]
11454,NaN,POINT(-3 19),12664.0,NaN,[7058]
11455,NaN,POINT(10 20),12664.0,NaN,[7058]
11456,NaN,POINT(18 18),12664.0,NaN,[7058]
11457,NaN,POINT(24 20),12664.0,NaN,[7058]

In [66]:
ufdf.to_csv('./output/unmatched_flares_with_harps.csv')

In [69]:
all_harps = []
for harp_list in ufdf['harps'].values:
    print harp_list
    all_harps.extend(harp_list)
all_harps = list( set( all_harps ) )
with open('./output/all_harps_combined', 'w') as file_handler:
    for item in all_harps:
        file_handler.write("{}\n".format(item))

[86]
[86]
[]
[]
[]
[]
[1621]
[1621]
[1621]
[1621]
[1621]
[1621]
[1621]
[1621]
[1621]
[1621]
[1621]
[1621]
[1621]
[1621]
[1621]
[1621]
[1621]
[1677]
[1677]
[1727]
[1750]
[1750]
[1750]
[1750]
[1744]
[1750]
[1750]
[1750]
[1750]
[1750]
[1744]
[1750]
[1750]
[1750]
[1744]
[1750]
[1750]
[1750]
[1795, 1789]
[1789]
[1795]
[1795]
[1795]
[1795]
[1795]
[1806]
[1806]
[1795, 1806]
[1795]
[1806]
[1795]
[1806]
[1795]
[1806]
[1795]
[1806]
[1806]
[1806]
[1806]
[1806]
[1807]
[1795]
[1806]
[1807]
[1807]
[1806]
[1806]
[1795]
[1806]
[1807]
[1807]
[1806]
[1807]
[1806]
[1806]
[1806]
[1806]
[1807]
[1806, 1807]
[1807]
[1807]
[1807]
[1806]
[1806]
[1806]
[1807]
[1806]
[1807]
[1807]
[1807]
[1807]
[1807]
[1806]
[1807]
[1807]
[1806]
[1807]
[1806]
[1807]
[1807]
[1807]
[1807]
[1807]
[1807]
[1807]
[1807]
[1807]
[1807]
[1807]
[1807]
[1807]
[1807]
[1807]
[1807]
[1806]
[1807]
[1807]
[1807]
[1807]
[1807]
[1807]
[1807]
[1807]
[1807]
[1807]
[1807]
[1807]
[1807]
[1806]
[1807]
[1807]
[1807]
[1807]
[1807]
[1807]
[1807]
[1807]
[1834, 1807]
[1807]
[1834, 1807]
[1807]
[1807]
[1807]
[1807]
[1807]
[1807]
[1807]
[1807]
[1807]
[1807]
[1807]
[1807]
[1807]
[1807]
[1807]
[1807]
[1807]
[1807]
[1807]
[1807]
[1807]
[1834]
[1834]
[1834]
[1834]
[1834]
[1834]
[1834]
[1834]
[1834]
[1834]
[1834]
[1834]
[1834]
[1834]
[1834]
[1834]
[1834]
[1834]
[1834]
[1834]
[1834]
[1834]
[1834]
[1834]
[1873]
[1873]
[1886]
[1886]
[1903]
[1873]
[1903]
[1907]
[1907]
[1903]
[1907]
[1907]
[1907]
[1903]
[1907]
[1907]
[1907]
[1907]
[1903]
[1903]
[1903]
[1903]
[1930]
[1930]
[1930]
[1907]
[1930]
[1930]
[1930]
[1930]
[1930]
[1930]
[1907]
[1907]
[1930]
[1907]
[1907]
[1930]
[1907]
[1930]
[1907]
[1930]
[1930]
[1930]
[1931]
[1907]
[1930]
[1930]
[1907]
[1930]
[1930]
[1931]
[1931]
[1931]
[1931]
[1930]
[1907, 1931]
[1931]
[1930]
[1930]
[1931]
[1931]
[1946]
[1946]
[1946]
[1946]
[1962]
[1962]
[1962]
[1962]
[1962]
[1959]
[1959]
[2329]
[2758]
[2758]
[2758]
[2758]
[2758]
[2758]
[2758]
[2758]
[2758]
[2758]
[2758]
[2758]
[2758]
[2758]
[2758]
[2809]
[2809]
[2809]
[2809]
[2758]
[2809]
[2809]
[2809]
[2809]
[2809]
[2809]
[2809]
[2852]
[2852]
[2852]
[2852]
[2852]
[2852]
[2852]
[2852]
[2852]
[2852]
[2852]
[2852]
[2852]
[2852]
[2852]
[2852]
[2852]
[2852]
[2852]
[2852]
[2852]
[2852]
[3520]
[3520]
[3520]
[3520]
[3520]
[3520]
[3520]
[3520]
[3520]
[3520]
[3563]
[3563]
[3563]
[3563]
[3563]
[3563]
[3563]
[3563]
[3542]
[3563]
[3563]
[3563]
[3563]
[3563]
[3563]
[3563]
[3563]
[3563]
[3563]
[3563]
[3563]
[3563]
[3563]
[3563]
[3563]
[3563]
[3563]
[3563]
[3563]
[3563]
[3563]
[3563]
[3563]
[3563]
[3563]
[3563]
[3563]
[3563]
[3563]
[3563]
[3563]
[3563]
[3563]
[3563]
[3856]
[3856]
[3856]
[3856]
[3856]
[3856]
[3856]
[3856]
[3856]
[3856]
[3856]
[3856]
[3856]
[3856]
[3856]
[3856]
[3856]
[3856]
[3856]
[3856]
[3856]
[3856]
[3856]
[3856]
[3856]
[3856]
[3856]
[4156]
[4225]
[4225]
[4225]
[4225]
[4225]
[4225]
[4225]
[4225]
[4225]
[4225]
[4225]
[4225]
[4225]
[4225]
[4225]
[4225]
[4225]
[4225]
[4225]
[4225]
[4225]
[4225]
[4225]
[4225]
[4225]
[4225]
[4225]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[4800]
[4800]
[4800]
[4800]
[4800]
[4800]
[4800]
[4817]
[4817]
[4817]
[4817]
[4817]
[4817]
[4817]
[4817]
[4817]
[4817]
[4817]
[4817]
[4817]
[4817]
[4817]
[4817]
[4817]
[4817]
[4800]
[4817]
[4817]
[4817]
[4817]
[4817]
[4817]
[4817]
[4817]
[4817]
[4817]
[4817]
[4920]
[4920]
[4920]
[4920]
[4920]
[4920]
[4920]
[4920]
[4920]
[4920]
[4920]
[4920]
[4920]
[4920]
[4920]
[4920]
[4920]
[4920]
[4920]
[4920]
[4920]
[4920]
[4920]
[4920]
[4920]
[4920]
[4920]
[4920]
[4920]
[4920]
[4920]
[4920]
[4920]
[4920]
[4920]
[4920]
[4920]
[4920]
[4920]
[4920]
[4920]
[4920]
[4920]
[4920]
[4920]
[4920]
[4920]
[4920]
[]
[5885]
[5885]
[5885]
[5885]
[5885]
[5885]
[5885]
[5885]
[5885]
[5885]
[5885]
[5885]
[5885]
[5885]
[5885]
[5885]
[5885]
[5885]
[5885]
[5885]
[5885]
[5885]
[5885]
[5885]
[5885]
[5885]
[5885]
[5885]
[5885]
[5885]
[5885]
[5885]
[5885]
[5885]
[5885]
[5885]
[5885]
[5885]
[5885]
[5885]
[5885]
[5885]
[5885]
[5885]
[5885]
[5885]
[5885]
[5885]
[5885]
[5885]
[5885]
[5885]
[5885]
[5885]
[5885]
[5885]
[5885]
[5885]
[5885]
[5885]
[5885]
[5885]
[5885]
[5885]
[5885]
[5885]
[5885]
[5885]
[5885]
[5885]
[5885]
[5885]
[5885]
[5885]
[5885]
[5885]
[5885]
[5885]
[5885]
[5885]
[5885]
[5885]
[5885]
[5885]
[5885]
[5885]
[5885]
[5885]
[5885]
[5885]
[5885]
[5885]
[5885]
[5885]
[5885]
[5885]
[5885]
[5885]
[5885]
[5885]
[6227]
[]
[]
[]
[]
[]
[]
[7050]
[7050]
[7050]
[7050]
[7050]
[7050]
[7050]
[7050]
[7050]
[7050]
[7050]
[7050]
[7058]
[7058]
[7058]
[7058]
[1806]
[1807]
[1903]
[2758]
[3520]
[3563]
[5885]
[5885]
[5885]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[1750]
[1750]
[1750]
[1744]
[1744]
[1744]
[1744]
[1744]
[1744]
[1750]
[1750]
[1750]
[1750]
[1744]
[1750]
[1744]
[1750]
[1750]
[1750]
[1750]
[1750]
[1744]
[1744]
[]
[1750]
[]
[1744]
[1750]
[]
[]
[1750]
[]
[1750]
[1750]
[1750]
[1750]
[1750]
[1750]
[1750]
[1750]
[1750]
[1750]
[1750]
[]
[]
[1806]
[1807]
[1807]
[1807]
[]
[1807]
[]
[1807]
[1807]
[]
[1807]
[1807]
[1806]
[1834]
[1807]
[1807]
[]
[1807]
[1807]
[1807]
[1807]
[]
[1807]
[1807]
[1807]
[1807]
[1807]
[1807]
[1834]
[1834]
[1834]
[1834]
[1806]
[1807]
[1807]
[1834]
[1834]
[1834]
[1834]
[1834]
[1834]
[1834]
[1834]
[1834]
[1834]
[1834]
[1834]
[1834]
[1807]
[1834]
[1834]
[1834]
[1834]
[1834]
[1834]
[]
[]
[]
[]
[1930]
[1930]
[1930]
[1930]
[1930]
[1930]
[1930]
[1930]
[1907]
[1930]
[1930]
[1930]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[1946]
[]
[]
[]
[1979]
[1946, 1951]
[]
[1946]
[]
[1979]
[1962]
[]
[]
[1962]
[]
[1990]
[1959]
[1959]
[1990]
[1990]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[2758]
[2758]
[2758]
[]
[2852]
[2852]
[2852]
[2852]
[2852]
[2852]
[2852]
[2852]
[2852]
[2852]
[2852]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[3066]
[3066]
[3066]
[3066]
[3066]
[3066]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[3263]
[3263]
[3263]
[3263]
[3263]
[]
[]
[3263]
[3263]
[]
[3263]
[]
[3263]
[3263]
[3263]
[]
[3263]
[3263]
[3263]
[3263]
[3263]
[3263]
[3263]
[3263]
[3263]
[3263]
[]
[]
[3263]
[3263]
[]
[]
[]
[]
[]
[3295]
[]
[3295]
[]
[]
[]
[3295]
[3295]
[3295]
[3295]
[3295]
[3295]
[3295]
[]
[3295]
[3295]
[3295]
[3295]
[3295]
[3295]
[3295]
[3295]
[]
[]
[3295]
[3295]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[3520]
[]
[3520]
[]
[3520]
[3563]
[3563]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[3856]
[3856]
[3856]
[3856]
[3856]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[4156]
[]
[4156]
[4156]
[4156]
[4156]
[]
[]
[4156]
[4156]
[4156]
[4156]
[]
[4156]
[]
[4225]
[4225]
[4225]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[4800]
[4920]
[4920]
[4920]
[4920]
[4920]
[4920]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[5885]
[5885]
[5885]
[5885]
[5885]
[5885]
[5885]
[5885]
[5885]
[5885]
[5885]
[5885]
[5885]
[5885]
[5885]
[5885]
[5885]
[5885]
[5885]
[5885]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[7058]
[7058]
[]
[]
[]
[]
[1621]
[1677]
[1750]
[1744]
[1744]
[1789]
[1807]
[1807]
[1834]
[1834]
[1834]
[1834]
[1834]
[1907]
[1930]
[1907]
[1931]
[1931]
[1946]
[1962]
[1962]
[1962]
[1990]
[2758]
[2758]
[3856]
[3856]
[3856]
[3856]
[4225]
[]
[4800]
[4817]
[]
[]
[]
[7058]
[7058]
[7058]
[7058]

In [75]:
import os.path
for harp in all_harps:
    print os.path.isfile('../sharps-headers/' + str(harp) + '.txt')
    print '\t',os.path.isfile('../new-data/' + str(harp) + '.csv')

True
	False
True
	False
True
	False
True
	False
True
	False
True
	False
True
	False
True
	False
True
	False
True
	False
True
	False
True
	False
True
	False
True
	False
True
	False
True
	False
True
	False
True
	False
True
	False
True
	False
True
	False
True
	False
True
	False
True
	False
True
	False
True
	False
True
	False
True
	False
True
	False
True
	False
True
	True
True
	False
True
	False
True
	False
True
	False
True
	False
True
	False
True
	False
True
	False
True
	False
True
	False
True
	False
True
	False